export const productsArray = [
    {
        id: 1,
        name: 'iPhone 13 Pro',
        description: 'This is iPhone 13 Pro',
        capacity: '256',
        type: 'phone',
        price: '1000',
    },
    {
        id: 2,
        name: 'iPhone 12 Pro',
        description: 'This is iPhone 12 Pro',
        capacity: '128',
        type: 'phone',
        price: '2000',
    },
    {
        id: 3,
        name: 'iPhone X',
        description: 'This is iPhone X',
        capacity: '64',
        type: 'phone',
        price: '500',
    },
    {
        id: 4,
        name: 'iPhone 13 Pro Max',
        description: 'This is iPhone 13 Pro Max',
        capacity: '512',
        type: 'phone',
        price: '2500',
    },
    {
        id: 5,
        name: 'iPhone 8 Plus',
        description: 'This is iPhone 8 Plus',
        capacity: '64',
        type: 'phone',
        price: '1000',
    },
    {
        id: 6,
        name: 'iPhone 8',
        description: 'This is iPhone 8',
        capacity: '32',
        type: 'phone',
        price: '500',
    },
]
